nav:
- Overview: index.md
- Authentication: authentication.md
- Versioning: versioning.md
- Intent Verification Rules: intent_verification_rules.md
- Trigger Manual Configuration Backup: manual_config_backup.md
- Retrieving Configurations: retrieving_configurations.md
- Retrieving Device JSON File: retrieving_device_json_file.md
- Retrieving Device Log File: retrieving_device_log_file.md
- Serial Numbers: serial_numbers.md
- Generate and Download Techsupport File via API: techsupport.md
- Path Lookup: Path_Lookup
- Settings: Settings
- Tutorials: Tutorials
- Snapshots: snapshots
