# includes/excludes all rules by default
default: true

# 4-space list indentation works best with MkDocs
#MD007:
#  indent: 4

# Remove line length limit - no one wants to hard wrap all their paragraphs
MD013: false

# Allow inline HTML
MD033: false

# We only allow fenced code blocks
#MD046:
#  style: fenced

# Disabled because of admonitions
# https://github.com/DavidAnson/markdownlint-cli2/issues/243
# https://github.com/DavidAnson/markdownlint-cli2/pull/133
MD046: false
