nav:
  - "Getting Started":
      - index.md
      - overview
      - "Platform First Steps": platform_first_steps
  - 'API': IP_Fabric_API
  - 'GUI': IP_Fabric_GUI
  - 'Settings': IP_Fabric_Settings
  - 'Administration': System_Administration
  - ...
