nav:
  - IP Fabric Integrations: index.md
  - NetBox: https://ip-fabric.gitlab.io/integrations/ipfabric-netbox
  - Python: python
  - ServiceNow: service-now
  - Splunk: https://ip-fabric.gitlab.io/integrations/splunk-ta-ip-fabric
  - Partner-Led Integrations:
      - Infoblox: https://ip-fabric.gitlab.io/integrations/ipfabric-infoblox
      - Nornir: nornir
      - Postman: postman
      - ...
