nav:
  - IP Fabric Integrations: index.md
  - Python: python
  - Dynamic Attributes: dynamic-attributes
  - Infoblox: infoblox
  - NetBox: netbox
  - Nornir: nornir
  - Postman: postman
  - ServiceNow: service-now
  - Splunk: splunk
  - ...
