nav:
  - IP Fabric Integrations: index.md
  - NetBox: netbox
  - Python: python
  - ServiceNow: service-now
  - Splunk: splunk
  - Not Maintained:
      - Dynamic Attributes: dynamic-attributes
      - Infoblox: infoblox
      - Nornir: nornir
      - Postman: postman
      - ...
